#!/usr/bin/env python
"""Build the DataBox Python engine into a standalone sidecar binary.

This script:
  1. Generates a cryptographically random static token
  2. Writes it to engine/token_preset.py (frozen-mode auth)
  3. Writes it to desktop/.env.local (Tauri dev-mode env)
  4. Builds the engine with PyInstaller
  5. Copies the binary to desktop/src-tauri/binaries/ with the correct
     target-triplet filename that Tauri's externalBin expects

Usage:
    python build_sidecar.py              # full build
    python build_sidecar.py --token-only # generate token files only
"""

from __future__ import annotations

import argparse
import os
import secrets
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENGINE_DIR = ROOT / "engine"
DESKTOP_DIR = ROOT / "desktop"
BINARIES_DIR = DESKTOP_DIR / "src-tauri" / "binaries"

SIDECAR_NAME = "databox-engine-x86_64-pc-windows-msvc.exe"


def generate_token() -> str:
    return secrets.token_hex(32)


def write_token_preset(token: str) -> Path:
    path = ENGINE_DIR / "token_preset.py"
    path.write_text(
        f"# Generated by build_sidecar.py. Do not edit.\n"
        f'STATIC_TOKEN = "{token}"\n',
        encoding="utf-8",
    )
    print(f"  [OK] {path}")
    return path


def write_env_local(token: str) -> Path:
    path = DESKTOP_DIR / ".env.local"
    path.write_text(
        f"# Generated by build_sidecar.py. Do not edit.\n"
        f'VITE_DATABOX_STATIC_TOKEN="{token}"\n',
        encoding="utf-8",
    )
    print(f"  [OK] {path}")
    return path


def build_pyinstaller() -> Path:
    dist_dir = ROOT / "pyinstaller_dist"
    work_dir = ROOT / "pyinstaller_build"
    spec_path = ROOT / "databox_engine.spec"

    shutil.rmtree(dist_dir, ignore_errors=True)
    shutil.rmtree(work_dir, ignore_errors=True)
    spec_path.unlink(missing_ok=True)

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",
        "--name", "databox-engine",
        "--distpath", str(dist_dir),
        "--workpath", str(work_dir),
        "--add-data", f"{ENGINE_DIR}{os.pathsep}engine",
        "--hidden-import", "uvicorn",
        "--hidden-import", "sqlalchemy",
        "--hidden-import", "pydantic",
        "--hidden-import", "fastapi",
        "--hidden-import", "watchfiles",
        "--hidden-import", "alembic",
        "--hidden-import", "psycopg2",
        "--hidden-import", "pymysql",
        "--hidden-import", "duckdb",
        str(ENGINE_DIR / "main.py"),
    ]
    print("  -> Running PyInstaller...")
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        print("  [FAIL] PyInstaller build failed", file=sys.stderr)
        sys.exit(result.returncode)

    built = dist_dir / "databox-engine.exe"
    if not built.exists():
        print(f"  [FAIL] Expected binary not found: {built}", file=sys.stderr)
        sys.exit(1)

    size_mb = built.stat().st_size / 1_048_576
    print(f"  [OK] Built {size_mb:.0f} MB binary")
    return built


def install_sidecar(binary: Path) -> Path:
    BINARIES_DIR.mkdir(parents=True, exist_ok=True)
    dest = BINARIES_DIR / SIDECAR_NAME
    shutil.copy2(binary, dest)
    print(f"  [OK] Sidecar -> {dest}")
    return dest


def main() -> None:
    parser = argparse.ArgumentParser(description="Build DataBox engine sidecar")
    parser.add_argument(
        "--token-only",
        action="store_true",
        help="Only generate token files, skip PyInstaller build",
    )
    args = parser.parse_args()

    print("=" * 55)
    print("DataBox Sidecar Builder")
    print("=" * 55)

    token = generate_token()
    print(f"\n[1/3] Token ({len(token)} hex chars)")
    write_token_preset(token)
    write_env_local(token)

    if args.token_only:
        print("\n  Done (token-only mode).")
        return

    print("\n[2/3] PyInstaller build")
    binary = build_pyinstaller()

    print("\n[3/3] Install to Tauri binaries")
    install_sidecar(binary)

    shutil.rmtree(ROOT / "pyinstaller_dist", ignore_errors=True)
    shutil.rmtree(ROOT / "pyinstaller_build", ignore_errors=True)
    (ROOT / "databox_engine.spec").unlink(missing_ok=True)

    print("\n" + "=" * 55)
    print("Sidecar build complete.")
    print(f"  {BINARIES_DIR / SIDECAR_NAME}")
    print("  Next: cd desktop && npm run tauri -- build")
    print("=" * 55)


if __name__ == "__main__":
    main()
