"""
DataBox Sidecar Builder Automation Script
Bakes compile-time secure token, triggers PyInstaller compilation, and formats Tauri binary target triplet.
"""
import os
import sys
import shutil
import secrets
import subprocess
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
ENGINE_DIR = ROOT_DIR / "engine"
DESKTOP_DIR = ROOT_DIR / "desktop"
BINARIES_DIR = DESKTOP_DIR / "src-tauri" / "binaries"


def get_target_triplet() -> str:
    """Detect local rustc target triplet dynamically."""
    try:
        res = subprocess.run(["rustc", "-vV"], capture_output=True, text=True, check=True)
        for line in res.stdout.splitlines():
            if line.startswith("host:"):
                return line.split(":", 1)[1].strip()
    except Exception as e:
        print(f"Warning: Failed to fetch host triplet via rustc -vV: {e}")
    
    # Platform-based fallback
    if sys.platform == "win32":
        return "x86_64-pc-windows-msvc"
    elif sys.platform == "darwin":
        return "x86_64-apple-darwin"
    return "x86_64-unknown-linux-gnu"


def main():
    print("=================================================================")
    print("   DataBox Standalone Engine Sidecar Packager V1.0")
    print("=================================================================")
    
    # 1. Generate compile-time security token
    token = secrets.token_hex(32)
    print(f"[+] Secure Build Token generated: {token[:8]}...{token[-8:]}")
    
    # 2. Write token preset to Python engine
    preset_file = ENGINE_DIR / "token_preset.py"
    preset_content = f'# Generated by build_sidecar.py. Do not edit.\nSTATIC_TOKEN = "{token}"\n'
    preset_file.write_text(preset_content, "utf-8")
    print(f"[+] Saved token preset module: {preset_file.relative_to(ROOT_DIR)}")
    
    # 3. Write token to React Vite .env.local
    env_file = DESKTOP_DIR / ".env.local"
    env_content = f"VITE_LOCAL_ENGINE_PORT=18625\nVITE_LOCAL_ENGINE_TOKEN={token}\n"
    env_file.write_text(env_content, "utf-8")
    print(f"[+] Synchronized frontend configuration: {env_file.relative_to(ROOT_DIR)}")
    
    # 4. Resolve output directory and triplet
    triplet = get_target_triplet()
    print(f"[+] Local Rust Host Triplet: {triplet}")
    BINARIES_DIR.mkdir(parents=True, exist_ok=True)
    
    # 5. Build Python executable using PyInstaller
    print("\n>>> Starting PyInstaller Compilation (This might take a moment)...")
    
    spec_name = "databox-engine"
    pyinstaller_cmd = [
        "pyinstaller",
        "--clean",
        "--onefile",
        f"--name={spec_name}",
        f"--distpath={BINARIES_DIR}",
        "--collect-all", "uvicorn",
        "--collect-all", "sqlglot",
        "--collect-all", "cryptography",
        "--collect-all", "pymysql",
        "--collect-all", "sshtunnel",
        "--collect-all", "keyring",
        str(ENGINE_DIR / "main.py")
    ]
    
    try:
        subprocess.run(pyinstaller_cmd, check=True)
        print("[+] PyInstaller compilation completed successfully!")
    except subprocess.CalledProcessError as e:
        print(f"[-] Error: PyInstaller exited with code {e.returncode}")
        sys.exit(e.returncode)
        
    # 6. Locate compiled binary and rename it to target triplet
    ext = ".exe" if sys.platform == "win32" else ""
    compiled_binary = BINARIES_DIR / f"{spec_name}{ext}"
    final_binary = BINARIES_DIR / f"{spec_name}-{triplet}{ext}"
    
    if compiled_binary.exists():
        if final_binary.exists():
            final_binary.unlink()
        compiled_binary.rename(final_binary)
        print(f"\n[★] Success! Tauri Sidecar Binary successfully bundled:")
        print(f"    -> {final_binary.relative_to(ROOT_DIR)}")
    else:
        print(f"[-] Error: Could not find compiled binary at {compiled_binary}")
        sys.exit(1)
        
    # 7. Clean up spec files and build directories
    print("\n>>> Cleaning up PyInstaller temporary artifacts...")
    spec_file = ROOT_DIR / f"{spec_name}.spec"
    if spec_file.exists():
        spec_file.unlink()
        
    build_dir = ROOT_DIR / "build"
    if build_dir.exists():
        shutil.rmtree(build_dir)
        
    print("[+] Workspace cleaned. Packaging complete!")
    print("=================================================================\n")


if __name__ == "__main__":
    main()
