"""Baseline database setup

Revision ID: 99b4fdab0781
Revises: 
Create Date: 2026-05-24 20:13:33.829051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b4fdab0781'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('db_type', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_ciphertext', sa.String(), nullable=False),
    sa.Column('password_nonce', sa.String(), nullable=False),
    sa.Column('password_key_version', sa.String(), nullable=False),
    sa.Column('ssh_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssh_host', sa.String(), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_username', sa.String(), nullable=True),
    sa.Column('ssh_password_ciphertext', sa.String(), nullable=True),
    sa.Column('ssh_password_nonce', sa.String(), nullable=True),
    sa.Column('ssh_pkey_path', sa.String(), nullable=True),
    sa.Column('ssh_pkey_passphrase_ciphertext', sa.String(), nullable=True),
    sa.Column('ssh_pkey_passphrase_nonce', sa.String(), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssl_ca_path', sa.String(), nullable=True),
    sa.Column('ssl_cert_path', sa.String(), nullable=True),
    sa.Column('ssl_key_path', sa.String(), nullable=True),
    sa.Column('ssl_verify_identity', sa.Boolean(), nullable=False),
    sa.Column('connection_mode', sa.String(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('env', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(), nullable=True),
    sa.Column('last_test_error', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['database_environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_sources_project_id'), ['project_id'], unique=False)

    op.create_table('database_environments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('runtime', sa.String(), nullable=False),
    sa.Column('engine_type', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('container_name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_ciphertext', sa.String(), nullable=False),
    sa.Column('password_nonce', sa.String(), nullable=False),
    sa.Column('datasource_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_health_status', sa.String(), nullable=True),
    sa.Column('last_health_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('database_environments', schema=None) as batch_op:
        batch_op.create_index('ix_database_environments_project', ['project_id'], unique=False)
        batch_op.create_index('ix_database_environments_status', ['status'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_status', ['status'], unique=False)

    op.create_table('backup_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('datasource_id', sa.String(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('backup_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['database_environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.create_index('ix_backup_records_created', ['created_at'], unique=False)
        batch_op.create_index('ix_backup_records_datasource', ['datasource_id'], unique=False)
        batch_op.create_index('ix_backup_records_project', ['project_id'], unique=False)

    op.create_table('golden_sqls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('golden_sql', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('golden_sqls', schema=None) as batch_op:
        batch_op.create_index('ix_golden_sqls_datasource', ['data_source_id'], unique=False)

    op.create_table('llm_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('prompt_template_hash', sa.String(), nullable=True),
    sa.Column('model_temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('submitted_sql', sa.Text(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('safe_sql', sa.Text(), nullable=True),
    sa.Column('executed_sql', sa.Text(), nullable=True),
    sa.Column('guardrail_result', sa.String(), nullable=False),
    sa.Column('guardrail_checks', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('connect_ms', sa.Integer(), nullable=True),
    sa.Column('guardrail_ms', sa.Integer(), nullable=True),
    sa.Column('execute_ms', sa.Integer(), nullable=True),
    sa.Column('fetch_ms', sa.Integer(), nullable=True),
    sa.Column('serialize_ms', sa.Integer(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('columns_returned', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_history', schema=None) as batch_op:
        batch_op.create_index('ix_query_history_created', ['created_at'], unique=False)
        batch_op.create_index('ix_query_history_datasource', ['data_source_id'], unique=False)

    op.create_table('schema_tables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('table_schema', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('table_comment', sa.String(), nullable=True),
    sa.Column('table_type', sa.String(), nullable=True),
    sa.Column('row_count_estimate', sa.Integer(), nullable=True),
    sa.Column('engine_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schema_tables', schema=None) as batch_op:
        batch_op.create_index('ix_schema_tables_datasource', ['data_source_id'], unique=False)

    op.create_table('table_design_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('table_comment', sa.String(), nullable=True),
    sa.Column('columns_json', sa.Text(), nullable=False),
    sa.Column('indexes_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_design_drafts', schema=None) as batch_op:
        batch_op.create_index('ix_table_design_drafts_project', ['project_id'], unique=False)

    op.create_table('schema_columns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('column_type', sa.String(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('column_default', sa.String(), nullable=True),
    sa.Column('column_comment', sa.String(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False),
    sa.Column('foreign_table_id', sa.String(), nullable=True),
    sa.Column('foreign_column_id', sa.String(), nullable=True),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['schema_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schema_columns', schema=None) as batch_op:
        batch_op.create_index('ix_schema_columns_table', ['table_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schema_columns', schema=None) as batch_op:
        batch_op.drop_index('ix_schema_columns_table')

    op.drop_table('schema_columns')
    with op.batch_alter_table('table_design_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_table_design_drafts_project')

    op.drop_table('table_design_drafts')
    with op.batch_alter_table('schema_tables', schema=None) as batch_op:
        batch_op.drop_index('ix_schema_tables_datasource')

    op.drop_table('schema_tables')
    with op.batch_alter_table('query_history', schema=None) as batch_op:
        batch_op.drop_index('ix_query_history_datasource')
        batch_op.drop_index('ix_query_history_created')

    op.drop_table('query_history')
    op.drop_table('llm_logs')
    with op.batch_alter_table('golden_sqls', schema=None) as batch_op:
        batch_op.drop_index('ix_golden_sqls_datasource')

    op.drop_table('golden_sqls')
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.drop_index('ix_backup_records_project')
        batch_op.drop_index('ix_backup_records_datasource')
        batch_op.drop_index('ix_backup_records_created')

    op.drop_table('backup_records')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_status')

    op.drop_table('projects')
    with op.batch_alter_table('database_environments', schema=None) as batch_op:
        batch_op.drop_index('ix_database_environments_status')
        batch_op.drop_index('ix_database_environments_project')

    op.drop_table('database_environments')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_project_id'))
        batch_op.drop_index(batch_op.f('ix_data_sources_environment_id'))

    op.drop_table('data_sources')
    # ### end Alembic commands ###
