#!/usr/bin/env python
"""Create the shared one-time credential used by source-mode Engine and Vite."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import secrets
import tempfile

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DESKTOP_DIR = ROOT / "desktop"
DEFAULT_ENGINE_PORT = 18_625


def generate_dev_token() -> str:
    return secrets.token_hex(32)


def write_frontend_env(
    token: str,
    *,
    desktop_dir: Path = DEFAULT_DESKTOP_DIR,
    engine_port: int = DEFAULT_ENGINE_PORT,
) -> Path:
    if len(token) != 64 or any(character not in "0123456789abcdef" for character in token):
        raise ValueError("Development token must be 32 lowercase hexadecimal bytes")
    if not 1 <= engine_port <= 65_535:
        raise ValueError("Engine port must be a valid TCP port")

    desktop_dir.mkdir(parents=True, exist_ok=True)
    destination = desktop_dir / ".env.local"
    content = (
        "# Generated by scripts/dev_environment.py. Do not edit.\n"
        f"VITE_LOCAL_ENGINE_PORT={engine_port}\n"
        f'VITE_LOCAL_ENGINE_TOKEN="{token}"\n'
    )
    descriptor, temporary_name = tempfile.mkstemp(
        dir=desktop_dir,
        prefix=".env.local.",
        suffix=".tmp",
        text=True,
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.chmod(temporary_path, 0o600)
        temporary_path.replace(destination)
    finally:
        temporary_path.unlink(missing_ok=True)
    return destination


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the shared DBFox source-mode development token",
    )
    parser.add_argument("--desktop-dir", type=Path, default=DEFAULT_DESKTOP_DIR)
    parser.add_argument("--engine-port", type=int, default=DEFAULT_ENGINE_PORT)
    args = parser.parse_args()

    token = generate_dev_token()
    write_frontend_env(
        token,
        desktop_dir=args.desktop_dir,
        engine_port=args.engine_port,
    )
    print(token)


if __name__ == "__main__":
    main()
