#!/usr/bin/env python
"""Extract a final Tauri installer and verify its frozen sidecar contract."""

from __future__ import annotations

import argparse
from contextlib import contextmanager
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from typing import Iterator

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import build_sidecar


FORBIDDEN_PACKAGE_DIRECTORIES = {
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "test",
    "tests",
}
FORBIDDEN_PACKAGE_SUFFIXES = {
    ".log",
    ".map",
    ".pyc",
    ".pyo",
    ".spec",
    ".tmp",
}


def _find_one(root: Path, pattern: str) -> Path:
    matches = sorted(root.glob(pattern))
    if not matches:
        raise RuntimeError(f"No release artifact matched {pattern} below {root}")
    if len(matches) > 1:
        raise RuntimeError(f"Expected one release artifact for {pattern}, found {len(matches)}")
    return matches[0]


@contextmanager
def extracted_installer(bundle_root: Path) -> Iterator[tuple[Path, Path]]:
    if sys.platform == "darwin":
        app = _find_one(bundle_root, "macos/*.app")
        installer = _find_one(bundle_root, "dmg/*.dmg")
        yield installer, app
        return

    with tempfile.TemporaryDirectory(prefix="dbfox-installer-extract-") as temporary:
        destination = Path(temporary)
        if sys.platform == "win32":
            installer = _find_one(bundle_root, "msi/*.msi")
            result = subprocess.run(
                ["msiexec.exe", "/a", str(installer), "/qn", f"TARGETDIR={destination}"],
                timeout=180,
            )
            if result.returncode != 0:
                raise RuntimeError(f"MSI administrative extraction failed: {result.returncode}")
        else:
            installer = _find_one(bundle_root, "appimage/*.AppImage")
            installer.chmod(installer.stat().st_mode | 0o100)
            env = os.environ.copy()
            env["APPIMAGE_EXTRACT_AND_RUN"] = "1"
            result = subprocess.run(
                [str(installer), "--appimage-extract"],
                cwd=destination,
                env=env,
                timeout=180,
            )
            if result.returncode != 0:
                raise RuntimeError(f"AppImage extraction failed: {result.returncode}")
        yield installer, destination


def _sidecar_candidates(root: Path) -> list[Path]:
    candidates: list[Path] = []
    for path in root.rglob("dbfox-engine*"):
        if not path.is_file() or "runtime-manifest" in path.name:
            continue
        if path.suffix.lower() in {".json", ".pdb"}:
            continue
        candidates.append(path)
    return sorted(candidates, key=lambda path: (len(path.parts), str(path)))


def verify_extracted_tree(
    root: Path,
    expected_manifest_path: Path,
    forbidden_values: tuple[bytes, ...] = (),
) -> dict[str, object]:
    expected = json.loads(expected_manifest_path.read_text(encoding="utf-8"))
    if expected.get("schema_version") != build_sidecar.ARTIFACT_MANIFEST_SCHEMA_VERSION:
        raise RuntimeError("Build artifact manifest was not generated by a final sidecar probe")

    bundled_manifests = sorted(root.rglob("dbfox-engine-runtime-manifest.json"))
    if len(bundled_manifests) != 1:
        raise RuntimeError(f"Expected one bundled runtime manifest, found {len(bundled_manifests)}")
    bundled = json.loads(bundled_manifests[0].read_text(encoding="utf-8"))
    if bundled != expected:
        raise RuntimeError("Bundled runtime manifest differs from the probed build manifest")

    candidates = _sidecar_candidates(root)
    matching = [
        path
        for path in candidates
        if build_sidecar._sha256(path) == expected.get("sidecar_sha256")
    ]
    if len(matching) != 1:
        raise RuntimeError(
            f"Expected one installer sidecar with hash {expected.get('sidecar_sha256')}, found {len(matching)}"
        )
    sidecar = matching[0]
    runtime = build_sidecar.probe_sidecar_runtime(sidecar)
    if runtime != expected.get("runtime"):
        raise RuntimeError("Extracted installer sidecar runtime differs from its artifact manifest")
    release_contracts = build_sidecar.probe_sidecar_release_contracts(sidecar)
    if release_contracts != expected.get("release_contracts"):
        raise RuntimeError("Extracted installer Sidecar release contracts differ from its artifact manifest")
    package_files = [path for path in root.rglob("*") if path.is_file()]
    forbidden_files = [
        path
        for path in package_files
        if _is_forbidden_package_file(path.relative_to(root))
    ]
    if forbidden_files:
        names = ", ".join(str(path.relative_to(root)) for path in forbidden_files[:10])
        raise RuntimeError(f"Installer contains forbidden development files: {names}")
    for forbidden in forbidden_values:
        if len(forbidden) < 16:
            raise RuntimeError("Forbidden package values must contain at least 16 bytes")
        matches = [
            path
            for path in package_files
            if _file_contains(path, forbidden)
        ]
        if matches:
            names = ", ".join(str(path.relative_to(root)) for path in matches[:10])
            raise RuntimeError(f"Installer contains a forbidden production value: {names}")
    return {
        "verified": True,
        "sidecar_path": str(sidecar),
        "sidecar_size_bytes": sidecar.stat().st_size,
        "sidecar_sha256": expected["sidecar_sha256"],
        "target_triplet": expected["target_triplet"],
        "sqlite_version": runtime["sqlite_version"],
        "sqlite_source_id": runtime["sqlite_source_id"],
        "package_files_scanned": len(package_files),
        "forbidden_file_hits": 0,
        "forbidden_value_hits": 0,
    }


def _is_forbidden_package_file(relative_path: Path) -> bool:
    parts = {part.lower() for part in relative_path.parts[:-1]}
    name = relative_path.name.lower()
    return (
        bool(parts & FORBIDDEN_PACKAGE_DIRECTORIES)
        or name == ".env"
        or name.startswith(".env.")
        or relative_path.suffix.lower() in FORBIDDEN_PACKAGE_SUFFIXES
    )


def _file_contains(path: Path, needle: bytes) -> bool:
    overlap = len(needle) - 1
    previous = b""
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            content = previous + chunk
            if needle in content:
                return True
            previous = content[-overlap:] if overlap else b""
    return False


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--bundle-root",
        type=Path,
        default=Path("desktop/src-tauri/target/release/bundle"),
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=build_sidecar.RUNTIME_MANIFEST_PATH,
    )
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--forbidden-value-env",
        help="Read a release-test sentinel from this environment variable and reject it in the bundle",
    )
    args = parser.parse_args()

    forbidden_values: tuple[bytes, ...] = ()
    if args.forbidden_value_env:
        value = os.environ.get(args.forbidden_value_env)
        if not value:
            raise RuntimeError(
                f"Release sentinel environment variable is missing: {args.forbidden_value_env}"
            )
        forbidden_values = (value.encode("utf-8"),)

    with extracted_installer(args.bundle_root.resolve()) as (installer, root):
        result = verify_extracted_tree(
            root,
            args.manifest.resolve(),
            forbidden_values=forbidden_values,
        )
        result["installer"] = str(installer)
        result["installer_size_bytes"] = installer.stat().st_size
        result["installer_sha256"] = build_sidecar._sha256(installer)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(result, ensure_ascii=False, sort_keys=True))


if __name__ == "__main__":
    main()
